const PRODUCTS_CONSTANTS ={
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    GET_ALL_PRODUCTS_SUCCESS:"GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE:"GET_ALL_PRODUCTS_FAILURE",
}


export default PRODUCTS_CONSTANTS;