


const ADD_PRODUCT={
    ADD_PRODUCT_REQUEST:"ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS:"ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE:"ADD_PRODUCT_FAILURE",
    ADD_PRODUCT_PRICE:"ADD_PRODUCT_PRICE"
}

export default ADD_PRODUCT